CONFIG_COAP_SERVER_HOSTNAME="californium.eclipseprojects.io"
CONFIG_COAP_SERVER_PORT=5684
CONFIG_COAP_DTLS_PSK_IDENTITY="Client_identity"
CONFIG_COAP_DTLS_PSK_SECRET="secretPSK"
# enter 73656372657450534B in Wireshark DTLS PSK decoder field
CONFIG_MBEDTLS_SSL_DTLS_CONNECTION_ID=y
CONFIG_MBEDTLS_SSL_EXTENDED_MASTER_SECRET=y
CONFIG_MBEDTLS_SSL_SERVER_NAME_INDICATION=n


